spring.application.name: composer-v1-generator-service
server.port: 7002
app:
  composer-service:
    host: localhost
    port: 7000
  composition-service:
    host: localhost
    port: 7001
  generation-service:
    host: localhost
    port: 7002
logging:
  level:
    root: info
    web: debug
    sql: debug
    com.reynolds.composer.v1: debug
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: debug
---
spring.config.activate.on-profile: docker
server.port: 8080