spring.application.name: composer-v1-generator-service
server.port: 7002
app:
  composition-service:
    host: localhost
    port: 7001
logging:
  level:
    root: info
    web: debug
    sql: debug
    com.reynolds.composer.v1: debug
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: debug
---
spring.config.activate.on-profile: docker
server.port: 8080
app:
  composition-service:
    host: ${COMPOSITION_SERVICE_HOSTNAME:composition-microservice}
    port: 8080

spring.data.mongodb:
  host: ${DB_HOST:localhost}
  port: 27017
  username: mongoadmin
  password: secret
  authentication-database: admin